version: '2.1'

services:

  airflow:
    hostname: airflow
    container_name: airflow
    image: airflow-pgt:0.01
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 28080:8080
    volumes:
      - type: bind
        source: ./airflow/airflow-dags/
        target: /home/dags/
        read_only: false
      - type: bind
        source: ./airflow/airflow-code/
        target: /home/code/
        read_only: false
    depends_on:
      - postgresql-airflow

  postgresql-airflow:
    hostname: postgresql-airflow
    container_name: postgresql-airflow
    image: postgresql-airflow-pgt:0.01
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 15432:15432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.8
    restart: always
    ports:
      - 8088:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgt@pgt.com
      - PGADMIN_DEFAULT_PASSWORD=pgt
    depends_on:
      - postgresql-airflow